FROM diamol/golang AS builder

COPY main.go .
RUN go build -o /web/server

# app
FROM diamol/base

WORKDIR web

CMD ["/web/server"]
ENV USER=sixeyed
EXPOSE 80

COPY --from=builder /web/server .
RUN chmod +x server

COPY index.html .